language: node_js
sudo: required
node_js: 10.19.0
cache: npm
dist: trusty
env:
  global:
      -SAUCE_USERNAME: 'sso-sap-I505386'
      -SAUCE_ACCESS_KEY: 'b5380f8c-f030-4960-b95d-a212f744eba0'

addons:
    chrome: stable
    sauce_connect:
    username: 'sso-sap-I505386'
    access_key: 'b5380f8c-f030-4960-b95d-a212f744eba0'

git:
  depth: false
script:
  - npm run build-all
jobs:
  include:
  - stage: "Lint and Test"
    before_script: export NODE_OPTIONS='–--max_old_space_size=4096'
    script: npm run lint && npm run test && npm run test:coveralls && npm run build-pack-library && npm run test:saucelabs
  - stage: "Pre-release"
    if: branch = master AND type = push
    before_script: export NODE_OPTIONS='–--max_old_space_size=4096'
    before_deploy:
    - git checkout master
    - bash ./ci-scripts/setup-npm.sh
    deploy:
    - provider: script
      script: bash ./ci-scripts/publish.sh
      skip_cleanup: true
  - stage: "Archive-pre-release"
    if: branch = archive-ngx-core-ng*
    before_script: export NODE_OPTIONS='–--max_old_space_size=4096'
    before_deploy:
    - git checkout archive-ngx-core-ng7
    - bash ./ci-scripts/setup-npm.sh
    deploy:
    - provider: script
      script: bash ./ci-scripts/publish.sh
      skip_cleanup: true
      on:
        all_branches: true
  - stage: "Release"
    if: branch = tmp_branch_for_automated_release_do_not_use
    before_script: export NODE_OPTIONS='-–-max_old_space_size=4096'
    before_deploy:
    - git config --add remote.origin.fetch +refs/heads/*:refs/remotes/origin/*
    - git fetch
    - git checkout master
    - bash ./ci-scripts/setup-npm.sh
    deploy:
    - provider: script
      script: bash ./ci-scripts/publish.sh
      skip_cleanup: true
      on:
        all_branches: true
  - stage: "Archive-release"
    if: branch = archive_tmp_branch_for_automated_release_do_not_use
    before_script: export NODE_OPTIONS='–--max_old_space_size=4096'
    before_deploy:
    - git config --add remote.origin.fetch +refs/heads/*:refs/remotes/origin/*
    - git fetch
    - git checkout archive-ngx-core-ng7
    - bash ./ci-scripts/setup-npm.sh
    deploy:
    - provider: script
      script: bash ./ci-scripts/publish.sh
      skip_cleanup: true
      on:
        all_branches: true
notifications:
  email:
    on_failure: always
    on_success: change
  slack:
    rooms:
      - ui-fundamentals:zVRyxlqkYnQFD7p8QHkWM8Fd#ngx-automated
